### ISSUE TITLE
Cant select a whole item with a HierarchyId field

### ISSUE THREAD

**Issue by jjavierdguezas** [efcore/EFCore.SqlServer.HierarchyId#32] opened 2020-11-10 14:34 UTC
When I query an object with a HierarchyId field I get

>Expression of type 'System.Object' cannot be used for parameter of type 'System.Data.SqlTypes.SqlBytes' of method 'Microsoft.EntityFrameworkCore.HierarchyId fromProvider(System.Data.SqlTypes.SqlBytes)'

If I select just some other properties or transform the object with the HierarchyId as string it works

This issue makes difficult to update entities with HierarchyId props

>"Microsoft.EntityFrameworkCore.Tools" Version="3.1.9"
>"Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9"
>"EntityFrameworkCore.SqlServer.HierarchyId" Version="1.1.1"
>
> TargetFramework: netcoreapp3.1

**Comment by smitpatel** [comment] 2020-11-10 17:14
@jjavierdguezas - Share a runnable code which shows issue you are seeing.

**Comment by jjavierdguezas** [comment] 2020-11-10 23:16
Hi @smitpatel 
Here is an executable code as close to my current (and bigger) project as possible [HierarchyIdIssueTest.zip](https://github.com/efcore/EFCore.SqlServer.HierarchyId/files/5520692/HierarchyIdIssueTest.zip)

Creating that project I found that the issue appears when I use `.EnableRetryOnFailure()` (read more [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder.enableretryonfailure?view=efcore-3.1))

I have configured (via `#if DEBUG ... #endif`) that some functions are enabled when debugging the application:

```csharp
        public TestDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();
#if DEBUG
            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.EnableDetailedErrors();
#endif
            var builder = new ConfigurationBuilder()
                             .SetBasePath(Directory.GetCurrentDirectory())
                             .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            builder.AddEnvironmentVariables();
            var configuration = builder.Build();

            optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), o => o
                .UseHierarchyId()
                .MigrationsAssembly(typeof(TestDbContext).Assembly.GetName().Name)
#if DEBUG
            .EnableRetryOnFailure()
#endif
            );
            return new TestDbContext(optionsBuilder.Options);
        }
```

if you comment the  `.EnableRetryOnFailure()` the code works but if it is present the Exception is thrown

**Comment by smitpatel** [comment] 2020-11-10 23:24
Duplicate of #24

**Closed by smitpatel** 2020-11-10 23:24 UTC

**Comment by jjavierdguezas** [comment] 2020-11-10 23:31
ohh didn't see that, thanks a lot @smitpatel 
It would be nice to fix or patch this, because updating entities with this issue is difficult (you need to load an entity without the Hierarchy and attach it and mark the properties as modified, etc)

**Comment by smitpatel** [comment] 2020-11-10 23:59
The core issue is in underlying EF Core code so if it is patched there, it will work here directly.
I would defer to @bricelam to decide if we want to patch something here.
